spring:
  config:
    activate:
      on-profile: dev

  data:
    mongodb:
      authentication-database: admin
      uri: ${SPRING_DATA_MONGODB_URI}

app:
  cookie:
    secure: ${APP_COOKIE_SECURE}
