spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${SPRING_DATA_MONGODB_URI}

server:
  port: 8082

family-cookbook:
  app:
    jwt-cookie-name: TFC
    jwt-secret: ${JWT_SECRET}
    jwt-expiration-ms: 1800000  # 30 minutes for access token
    jwt-refresh-expiration-ms: 1209600000  # 14 days for refresh token

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.mbapps.rc.provider: INFO

app:
  cookie:
    secure: ${APP_COOKIE_SECURE:true}
