spring:
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb+srv://TestUser:e5u092miXnwWe3WO@b-m-apps-recipe.m919agk.mongodb.net/RecipeCentral

server:
  port: 8082

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.mbapps.rc.provider: DEBUG

#  spring.data.mongodb.authentication-database=admin
#  spring.data.mongodb.database=demo-db
#  spring.data.mongodb.uri=mongodb://username:password@localhost:27018/${spring.data.mongodb.database}?authSource=${spring.data.mongodb.authentication-database}&readPreference=primaryPreferred&directConnection=true